### ISSUE TITLE
The routing does not work

### ISSUE THREAD

**Issue by csu6** [juanmesa2097/angular-boilerplate#121]
Hi,

I try to access different link, but it seems that the routing doesn't work, for example:
https://angularboilerplate.netlify.app/sign-in
https://angularboilerplate.netlify.app/sign-up

Thank you

John

**Comment by juanmesa2097** [comment]
Hi John. This kind of behavior is because you're supposed to be logged in and you shouldn't be able to access those routes when you already have access.

# Explanation

I removed the auth service since this project should be easy to connect with any state manager like Akita, Ngxs, or Ngrx, so later on you don't have the hassle to manually remove services that you won't use. Being told that, there are two guards that protect the routes.

You can find those guards in the following locations:

```console
src\app\@core\guards/auth.guard.ts     // does not allow the user to access admin pages
src\app\@core\guards/no-auth.guard.ts     // does not allow the user to access +auth module pages like (sign in, sign up, forgot password, etc.)
```

The trouble you're having is due to the `no-auth.guard.ts`, there's a constant called isLoggedIn set to true, but this should be connected with your own implementation of the auth service, and the auth service should be able to check if there's a token stored in the local storage.

# Solutions

- Set the const isLoggedIn equal to false.
- Go to `src\app\app-routing.module.ts` and comment the "canActivate" property in the Auth module, so it won't validate the auth routes until you have your auth service implementation.

```ts
{
  path: Path.Auth,
  //canActivate: [NoAuthGuard],
  loadChildren: () => import('./+auth/auth.module').then((m) => m.AuthModule),
},
```

Let me know if you have any trouble at all & I'll be happy to help. Also, if you have any suggestions or want to contribute, you're welcome to do it.

**Comment by s1eeper888** [comment]
I just tried a setTimeout for 3000ms to simulate a sign in.. Once resolved - I try a router.navigate[Path.Dashboard] (even tried 'app/dashboard'..  Implemented own auth service so that both guards (NoAuthGuard, AuthGuard) checks for it.

Behavior: app component destroys ng-template router outlet, shows feature outlet. but router navigates to dashboard. the feature outlet shows the "app header" and router outlet stays on sign in screen.

According to numerous threads on stackoverflow - you can't have 2 router outlets that are primary on the root component. I don't think this works. If you have a working version, please send me stackblitz/link. Thanks

**Comment by juanmesa2097** [comment]
Hi @s1eeper888,

I don't really like using multiple router-outlets because it looks really messy & unpredictable. I think the async pipe subscription is way more clear and concise.

Since there are people having this issue, I just uploaded a demonstrable example of this feature, persisting the token in local storage. 

All changes made can be found in this [branch](https://github.com/juanmesa2097/angular-boilerplate/tree/example/auth) and in this [commit](https://github.com/juanmesa2097/angular-boilerplate/commit/e1cc8e5ddbd4b869b9b56a0021073fc5388a65ef)

Notice that if you try to access an admin route like `http://localhost:4200/settings/account`, you'll automatically be redirected to the sign-in page with a query parameter that holds the value of the return URL.

![image](https://user-images.githubusercontent.com/64181348/106040015-db4d1900-60a7-11eb-98c1-ec670d0f38c9.png)

This allows you to be more dynamic and access the page you were looking for after the login and not just be redirected to the dashboard every time.

# Steps to reproduce

- create an [auth service](https://github.com/juanmesa2097/angular-boilerplate/blob/example/auth/src/app/%2Bauth/services/auth.service.ts) that allows you to check the auth state through a behavior subject & also be responsible to store, get and remove the token from the local storage.
PD. here there would be additional service to sign-up & call services for forgot-password

- modify the [AuthGuard](https://github.com/juanmesa2097/angular-boilerplate/blob/example/auth/src/app/%40core/guards/auth.guard.ts) & the [NoAuthGuard](https://github.com/juanmesa2097/angular-boilerplate/blob/example/auth/src/app/%40core/guards/no-auth.guard.ts) in order to get the auth state through a getter called `isLoggedIn`

- Create a variable of type observable in the [app.component.ts](https://github.com/juanmesa2097/angular-boilerplate/blob/example/auth/src/app/app.component.ts) called isLoggedIn$. This will be useful to get the value of the behavior subject in the [auth service](https://github.com/juanmesa2097/angular-boilerplate/blob/example/auth/src/app/%2Bauth/services/auth.service.ts) and subscribe to it in the [HTML template](https://github.com/juanmesa2097/angular-boilerplate/blob/example/auth/src/app/app.component.html) through an async pipe.
PD. this will be useful to hide or show the header & footer.

- Add a button to call the sign-in method in the auth service. [See it here](https://github.com/juanmesa2097/angular-boilerplate/blob/example/auth/src/app/+auth/pages/sign-in/sign-in.page.ts)

- To logout, remember this repository follows the pure & smart components pattern, so the header shouldn't be responsible for calling any services. It can only emit. [Header emission](https://github.com/juanmesa2097/angular-boilerplate/blob/example/auth/src/app/%40components/header/header.component.ts). Listen to the emission in the [app-component](https://github.com/juanmesa2097/angular-boilerplate/blob/example/auth/src/app/app.component.ts) and call the logout method from there.

You can find a preview deployment in this URL: https://6011bf0a111b0b0007bc939d--angularboilerplate.netlify.app

## Things to keep in mind:

- You can access the [index page](https://6011bf0a111b0b0007bc939d--angularboilerplate.netlify.app) even when you're not logged in since that page is supposed to be public & informative.
- You can reload the page & the auth state will be persisted.
- After you're logged in, if you try to access auth pages like (sign-in, sign-up, forgot-password, etc.) you'll be redirected to the dashboard page.

If you need any help let me know.

**Comment by s1eeper888** [comment]
Thanks, I really like the boilerplate you got here. Good patterns/tooling. Will try to reproduce right now, and will get back to you. Thanks

**Comment by juanmesa2097** [comment]
Thank you for your kind words. It is always open to improvement.

>"Trying to figure out how this current route config would work without a public page. If the user isn't logged in at all, I just want to redirect them to the auth/sign-in page."

For that, you just need to remove the lazy loaded module from the [app-routing.module](https://github.com/juanmesa2097/angular-boilerplate/blob/main/src/app/app-routing.module.ts)

![image](https://user-images.githubusercontent.com/64181348/106054364-e741d680-60b9-11eb-8326-fddc9ffd474c.png)

**Comment by s1eeper888** [comment]
Can you explain the need for an seoservice? I thought SPA's are not crawled

**Comment by juanmesa2097** [comment]
@s1eeper888 the SEO service allows you to change the title, metatags, and robots of a certain route.

if you'd want to change the title & description of some page you would need to inject the title & meta services

```ts
export class SomePage implements OnInit {    
  constructor(private titleService: Title, private meta: Meta) {
    this.titleService.setTitle("Some title");
    this.meta.updateTag({ name: 'description', content: 'Some description'})
  }
}
```

With the SEO service, you can define those in the page route in the data object.

```ts
export const SOME_PAGE_ROUTE: Route = {
  path: Path.SomePage,
  component: SomePage,
  data: {
    title: 'Some title',
    description: 'Some description'
  },
};
````

That's just a matter of preference. If you want to go with the first option, you can just remove the SEO service.

**Comment by juanmesa2097** [comment]
I just saw this
>"*figured it out, got it working :). I just removed the Auth Route Object and everything looks to be working. Any reason why relativeLinkResolution: 'legacy', is set ?"

I think that option was set automatically when I updated the project to Angular 11

**Comment by s1eeper888** [comment]
> @s1eeper888 the SEO service allows you to change the title, metatags, and robots of a certain route.
> 
> if you'd want to change the title & description of some page you would need to inject the title & meta services
> 
> ```ts
> export class SomePage implements OnInit {    
>   constructor(private titleService: Title, private meta: Meta) {
>     this.titleService.setTitle("Some title");
>     this.meta.updateTag({ name: 'description', content: 'Some description'})
>   }
> }
> ```
> 
> With the SEO service, you can define those in the page route in the data object.
> 
> ```ts
> export const SOME_PAGE_ROUTE: Route = {
>   path: Path.SomePage,
>   component: SomePage,
>   data: {
>     title: 'Some title',
>     description: 'Some description'
>   },
> };
> ```
> 
> That's just a matter of preference. If you want to go with the first option, you can just remove the SEO service.

I get the functionality but whats the use case if spa's are not crawled?

**Comment by juanmesa2097** [comment]
@s1eeper888 the title is a visible part of your application and a visible part of your browser history, so you don't want that to always be **Angular Boilerplate**

![image](https://user-images.githubusercontent.com/64181348/106367612-e5725000-6311-11eb-91a6-3c8715815246.png)

When you integrate **Angular Universal** into this project, this service is a good fit.

I read recently that Google is now able to render crawl SPA pages, so we'll see.

**Comment by s1eeper888** [comment]
@juanmesa2097 routing strategy seems to break due to router entering an infinite loop when noAuthGuard is doing an async operation, for example rather checking whats in the subject on load- what if we want the page to survive page refreshes by checking a session on the server.. sync operations seems to work fine but not async

`const test = () => {
  return new Promise((res, rej) => {
    setTimeout(() => {
      res(true);
    });
  });
};

async canActivate() {
  const isLoggedIn = await test();
    if (isLoggedIn) {
      this.router.navigate([Path.App]);
      return false;
    }
    return true;
}`
