### ISSUE TITLE
Cache browser after deployment

### ISSUE THREAD

**Issue by mbvb1223** [juanmesa2097/angular-boilerplate#376]
Hi all, 

I have an issue related to cache.
I used this command to build production: `ng build --aot --configuration=production --output-hashing=all --base-href=https://mbvb1223.github.io/`

1. I changed something (add a new text...) at `index.html` (or some html component files: `contest-list.component.html`) 
2. When I access https://mbvb1223.github.io, there is no change. 
3. I have to refresh many times and sometimes need to press `shift + f5` then the new added text will be shown

Not sure this issue is related to this boilerplate or not? If anyone knows about this issue, please advise me

**Comment by mbvb1223** [comment]
I deployed into google firebase, it seems google firebase has some cache config. I will investigate more about it

**Comment by juanmesa2097** [comment]
Hi @mbvb1223, sorry for the late response. 

May I ask you which Angular version are you using and a screenshot of the content of your dist folder?

I've used this boilerplate for some projects and never have had any cache-related issues deploying to Vercel, Azure, or Netlify since ng build hashes the lazy chunk files as follows: 

![image](https://user-images.githubusercontent.com/64181348/119296229-2e7e4500-bc1e-11eb-9645-88a75d6fa945.png)

So the browser has to download the file again because it has a new name.

Please, let me know if you still need help with this & if you do, please, feel share a project where I can reproduce this issue.

Note: if you're generating your projects from a fork & the fork is outdated, you could try to update it to the latest Angular 12 version with the new GitHub option: "Fetch and merge"

![image](https://user-images.githubusercontent.com/64181348/119297029-c2044580-bc1f-11eb-8ca2-c220ae1f5073.png)


Regards.
