### ISSUE TITLE
Husky hooks when make a commit message

### ISSUE THREAD

**Issue by klymenko-oleksandr** [juanmesa2097/angular-boilerplate#498]
Hi, can you help with running Husky?
I use WebStorm:
1. Clone boilerplate repo
2. Install dependencies
3. Make double quotes in `selector: "app-root",`
4. Create commit
5. The output below:
```
alex@MacBook-Pro-Alexandr-2 angular-boilerplate % git commit -m "test commit"
hint: The '.husky/pre-commit' hook was ignored because it's not set as executable.
hint: You can disable this warning with `git config advice.ignoredHook false`.
hint: The '.husky/commit-msg' hook was ignored because it's not set as executable.
hint: You can disable this warning with `git config advice.ignoredHook false`.
[main fb8f0d5] test commit
1 file changed, 1 insertion(+), 1 deletion(-)
```
What I need to do for running husky?

**Comment by klymenko-oleksandr** [comment]
@juanmesa2097 can you help with this issue?

**Comment by juanmesa2097** [comment]
Hey, Husky is installed with the "postinstall" script so you shouldn't have to do anything to get it working.

It seems you need to make each hook executable in macOS with the following command:

`chmod +x .husky/pre-commit`

Could you please try this & tell me if it works?

https://stackoverflow.com/questions/67063993/sh-husky-command-not-found

**Comment by klymenko-oleksandr** [comment]
Thanks, after I run `chmod +x .husky/pre-commit` pre-commit hook works 👍 
So should I run it for each hook? to make it executable?

And one more questions:
1. We have prettier in the boilerplate - why we don't use/run it by default on pre-commit?
2. Do you have some explanation why some elements are placed inside some elements => for example `@core` folder I think we use for global stuff (and global services === with `providedIn: 'root'`) But I see that `AuthService` is also global but it placed inside pages/auth folder -- why?

**Comment by juanmesa2097** [comment]
@klymenko-oleksandr  Yes, I think you just have to run that command once for each hook to give them execution rights.

1. Yes, we can lint the code by adding the script in the pre-commit hook

```sh
# /angular-boilerplate/.husky/pre-commit.sh

#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

yarn test:unit
yarn lint
```

The problem with that approach is that Angular is way too slow, so it would take time to lint all the files.

The solution is to use a dependency called lint-staged, so you just lint the git-staged files (*let me know if you want to submit a PR to add this feature*).

2. Since Angular 6, `provideIn: 'root'` is the most efficient way to provide services in Angular. I don't really use the providers' array anymore. 

You're right, `AuthService` is a global service but this project follows the "Module encapsulation" principle, so if an Auth module exists, the AuthService should be within that module because it's the most logical way to relate it, even though it's not inside the providers array. You can take for example the Seo or Theme services; those are not related to any module, so they're in the core module.

By the way, the AuthService will disappear once an optional state-management feature is added to this project. In the meantime, that service only has an illustration purpose on how to handle the authentication state.

**Comment by klymenko-oleksandr** [comment]
I'll try to create a PR during this week (<run prettier for formatting files & run lint for check eslint errors> -- only for staged files)
