### ISSUE TITLE
Change the language via routing

### ISSUE THREAD

**Issue by thangaraja** [juanmesa2097/angular-boilerplate#59]
How to change the language at run time? Is there a way to control the language via routing?

Eg.

domain.com  --> Set the default language. i.e **english**
fr.domain.com or domain.com/fr --> Set the language **French**
es.domain.com or domain.com/es  --> Set the language **Spanish**

**Comment by juanmesa2097** [comment]
@thangaraja if you want to do it the Angular way, you need to take the i18n approach (which this project has) and follow the next steps.

1. Set the `i18n` directive in all the texts you want to translate.

2. Run the `npm run extract` command which takes the messages from the i18n directives and puts them into XLIFF files where you need to manually translate them or use a third party translator. 
*messages: (https://github.com/juanmesa2097/angular-boilerplate/tree/main/src/locale)*

3. Run the `npm run build:i18n` command to generate separated compilations, so your dist folder will end up with something like this:
```
dist/en
dist/es
dist/fr
```

Each compilation should go into virtual sub-directories when you deploy your app.

## When to use

If your app is small, you probably want to use runtime translations with a library like [ngx-translate](https://github.com/ngx-translate/core) since there's no much content to translate but If your app is big, the i18n approach is more recommendable because you'll have the texts already translated when the pages load.

This project helps you with the base set up and the commands. 

Right now I'm too busy to work on a working example with language switcher and sub-directories configuration, but I'll definitely add it soon, plus, I'll add docs for this and other features and improve the README, so if you're interested in that, you can watch for notifications in this repository.
