### ISSUE TITLE
How to import all material module globally ? 

### ISSUE THREAD

**Issue by MrTAN1AX** [juanmesa2097/angular-boilerplate#626]
I don't see the app.module file...

```
import { MaterialModule } from './material-module';

@NgModule({
  declarations: [
  ....
  ],
  imports: [
    ....
    MaterialModule,
    ....
  ],
})
export class AppModule { } 
```

**Comment by MrTAN1AX** [comment]
I don't see the app.module file...

```
import { MaterialModule } from './material-module';

@NgModule({
  declarations: [
  ....
  ],
  imports: [
    ....
    MaterialModule,
    ....
  ],
})
export class AppModule { } 
```

**Comment by juanmesa2097** [comment]
@MrTAN1AX this project is using the new approach of [standalone components](https://angular.io/guide/standalone-components) instead of NgModules. If you want to import a module globally you need to use the `importProvidersFrom` function. Check [this](https://github.com/juanmesa2097/angular-boilerplate/blob/ce43819465c8ecb8d6d94b0fdc4f94c6ecba5817/src/main.ts#L16) for reference.

```ts
importProvidersFrom(MaterialModule)
```

**Comment by MrTAN1AX** [comment]
Thanks for your fast reply.

I will definitely check it, I'm a little bit confuse about this approach, thanks you very much.

**Comment by juanmesa2097** [comment]
@MrTAN1AX my pleasure 🙂
